### ISSUE TITLE
propose NeuroX as a Google Summer of Code organization?

### ISSUE THREAD

**Issue by oserikov** [fdalvi/NeuroX#10]
Dear NeuroX authors! Both library and your papers are awesome.

Recently, I was involved in surveying models interpretation methods, as a part of [🤗 BigScience Workshop](https://bigscience.huggingface.co/). While the paper is under review, we definitely ended up with new hypotheses, and having an interpretation framework could ease the implementation of the experiment.

The framework you build here seems to be the cutting edge of nowadays models interpretation, so I was wondering whether you plan to implement the popular probing methods which arose recently (such as selectivity or attention probing). It seems so! I see adding the new methodologies in the roadmap.

I came to an idea, what if we use the [Google Summer of Code initiative](https://summerofcode.withgoogle.com) to boost the implementation of all the techniques?
Shortly, GSoC works like this: an open-source org provides tasks and mentorship, and Google provides some funding to motivate students from all around the world. Orgs first get acquainted with students, select those to work with, and supervise students' work during the summer.

I'm definitely interested in the advancement of the framework you build. I wonder if you find it interesting to propose NeuroX as a GSoC org.
Given I had experience leading the organization ([DeepPavlov](https://summerofcode.withgoogle.com/archive/2021/organizations/6618455117135872)) during the GSoC, I'll be happy if you find a use of my help.

You can always reach out to me over an email: `srkvoa@gmail.com`

**Comment by fdalvi** [comment]
Replied via email, thanks for reaching out!
