### ISSUE TITLE
13-dimensional array for BERT (12 layers)

### ISSUE THREAD

**Issue by Andrea-de-Varda** [fdalvi/NeuroX#7]
While BERT is a 12-layer model, the output of transformers_extractor has a shape of (n_tokens, 9984). 9984 divided by the hidden size 768 is 13. What am I missing? 

Thank you!

**Comment by fdalvi** [comment]
Hello Andrea!

By default, the embedding layer representations are also extracted (at index 0). The script (and the functions themselves) have an additional flag to ignore embeddings if you only care about the layers.

Hope this helps.

Best,
Fahim
